### ISSUE TITLE
env: node\r: No such file or directory

### ISSUE THREAD

**Issue by a186r** [cryptape/cita-truffle-box#28]
在mac和ubuntu 18.04下执行 `yarn migrate` 均出现以下错误：

```
yarn run v1.13.0
$ appchain-migrate migrate
env: node\r: No such file or directory
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by wuyuyue** [comment]
Sorry about that, I will update the line endings to LF instead of CRLF.

there is a workaround for it, 
"npx appchain-migrate migrate" instead of "yarn migrate"

**Comment by a186r** [comment]
@wuyuyue Thank you very much. It's working for me.
